Suppor Advertised prefixes
CiscoDevNet/terraform-provider-nxos pull request #164
Opened 2023-08-10 22:11 UTC by jgomezve

2023-08-10 22:13 UTC, jgomezve commented
The DME model mentions the attribute `evpn`, which is also configurable via cli `network x.x.x.x evpn`, but the API does not recognize this attribute. It is also not shown when using the NX-API Sandbox converter

2023-08-11 06:53 UTC, danischm requested changes

2023-08-11 06:53 UTC, danischm commented on gen/definitions/bgp_advertised_address.yaml
> +    description: 'The next-hop address tracking delay timer for critical next-hop reachability routes.'
I believe this needs to be updated.

2023-08-11 06:53 UTC, danischm commented on gen/definitions/bgp_advertised_address.yaml
> +  - BGP Address Family
We should then also update the "BGP Address Family" definition to list this as a child.

2023-08-11 06:53 UTC, danischm commented on gen/definitions/bgp_advertised_address.yaml
> +    description: 'Route map to modify attributese.'
typo

2023-08-11 13:44 UTC, danischm approved these changes

2023-08-11 13:45 UTC, merged