Added parameters for BGP Address family
CiscoDevNet/terraform-provider-nxos pull request #288
Opened 2024-12-28 19:20 UTC by rafmuller

Added as many of the parameters for BGP address family as I could validate in NXOS 9.3 CML instance I have. RAN tests against sandbox.

2024-12-29 16:48 UTC, rafmuller commented
I made another change. In BGP address family already done was the parameters of ```critNhTimeout``` and the non-critical. The problem is that they where set as integer values but the default is a string return from the API. While it works, every time you run the apply it wants to make a change because the return object from the API has the string while the default is numeric. 

To address this I changed this to a string, put the proper default values and then also had to change the examples to be different than the default values or the test code would also fail.

2025-01-08 18:16 UTC, danischm requested changes

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: adv_l2vpn_evpn
For the `tf_name` we try to avoid abbreviations and expand names where it makes sense. So I would suggest `advertise_l2vpn_evpn`.

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: adv_phyip_for_type5_routes
-> `advertise_physical_ip_for_type5_routes`

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: max_ext_ecmp_paths
-> `max_external_ecmp_paths`

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: max_ext_int_ecmp_paths
-> `max_external_internal_ecmp_paths`

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: max_eqcost_ecmp_paths
-> `max_local_ecmp_paths`

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: max_mixcost_ecmp_paths
-> `max_mixed_ecmp_paths`

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: def_inf_originate
-> `default_information_originate`

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: adv_only_act_routes
-> `advertise_only_active_routes`

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +  - nxos_name: tblMap
I think the feature on the cli is name "table-map", so maybe `table_map_route_map_name`.

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: vni_ethtag
-> `vni_ethernet_tag`

2025-01-08 18:16 UTC, danischm commented on gen/definitions/bgp_address_family.yaml
> +    tf_name: wait_igp_conv
-> `wait_igp_converged`

2025-01-12 10:28 UTC, danischm approved these changes

2025-01-12 10:28 UTC, merged